# Import Libraries and Set Random Seeds

This section imports all packages required for the context of this project

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import json
import pickle
import random as python_random
import os

Imports for Model Architecture

In [5]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
from keras.applications import ResNet50, InceptionResNetV2, VGG16, InceptionV3, DenseNet201
from keras import models, layers
from keras.optimizers import SGD
from keras.callbacks import EarlyStopping, ModelCheckpoint

Imports for Model Evaluation

In [ ]:
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report, f1_score
from sklearn.model_selection import train_test_split

Set random seeds for reproducible dataset

In [ ]:
np.random.seed(123)
python_random.seed(123)
tf.random.set_seed(1234)

Additional checks done to ensure required folders are already created, if not create it. The following folders will be checked.

1. `./weights`: Store the optimal weights of every model trained, named as `<model_name>.h5`
2. `./results`: Store the visualisation of each models performance
    * `./results/acc_loss_plots`: Store the loss and accuracy curves of each model's training
    * `./results/metrics`: Store the f1 and auc score comparison bar graphs
    * `./results/cm`: Store the confusion matrix generated by each model upon the validation set

In [ ]:
if not os.path.exists('./weights'):
    os.mkdir('./weights')

if not os.path.exists('./results'):
    os.mkdir('./results')

subfolders = ['acc_loss_plots', 'metrics', 'cm']
for sf in subfolders:
    filepath = './results/{}'.format(subfolders)
    if not os.path.exists(filepath):
        os.mkdir(filepath)

# Download and Preprocess Dataset

The dataset used, the IMDB-WIKI dataset faces can be downloaded using the following terminal command and preprocessed using the `mat.py` file which was obtained from the following repository: https://github.com/imdeepmind/processed-imdb-wiki-dataset/blob/master/mat.py

In [ ]:
!wget https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/static/wiki_crop.tar

In [ ]:
%run processed-imdb-wiki-dataset/mat.py

# Load Dataset

This section loads the dataset, splits the dataset into Training, Testing and Validation and loads these split datasets into separate `ImageDataGenerator`.

Additionally, existing results from previous sessions are loaded and saved for ease of collaboration and evaluation in the future. 

  Model histories are saved into a combined `histories.pickle` file as a dictionary with the following structure:
{
    `model_name`: Keras `history` callback object
}. 

  The maximum validation accuracy, F1 score and AUC_ROC score are saved into the `model_performance.csv` file in the following format: <`model_name`, `max_val_acc`, `f1_score`, `roc_auc`>.

In [ ]:
df = pd.read_csv('meta.csv')
df

The class distribution is explored to examine if any additional steps is required to ensure a balanced class distribution

In [ ]:
sns.countplot(x=df['gender'])
plt.show()

We see that this is an imbalanced dataset and hence requires a stratified split into training, testing and validation.

In [ ]:
# First take out 0.2 for test (this dataset will not be used in the training process)
train_df, test_df = train_test_split(df, test_size=0.2, random_state=0, stratify=df['gender'])
# Then split the remaining 0.8 into training and validation
train_df, val_df = train_test_split(train_df, test_size=0.3, random_state=0, stratify=train_df['gender'])

In [ ]:
train_datagen = ImageDataGenerator(rescale=1./255)
validation_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

Training, Validation and Testing geneerators are defined. In addition, a `predict_generator` is added on which model evaluation of generating the F1 and ROC_AUC scores is performed. This additional generator is required so that a comparison can be made by setting the parameter `shuffle=False`.

In [ ]:
def generate_data(img_size=224, batch_size=128):
  # data generator for training data
  train_generator = train_datagen.flow_from_dataframe(train_df, x_col="path", 
                                                      y_col="gender", 
                                                      target_size=(img_size,img_size), 
                                                      batch_size=batch_size, 
                                                      class_mode='binary')

  # data generator for validation data
  validation_generator = validation_datagen.flow_from_dataframe(val_df, x_col="path", 
                                                                y_col="gender", 
                                                                target_size=(img_size,img_size),
                                                                batch_size=batch_size, 
                                                                class_mode='binary')

  # data generator for validation data to be used for prediction
  predict_generator = validation_datagen.flow_from_dataframe(val_df, x_col="path", 
                                                             y_col="gender", 
                                                             target_size=(img_size,img_size),
                                                             batch_size=batch_size, 
                                                             class_mode='binary',
                                                             shuffle = False)

  # data generator for testing data
  test_generator = test_datagen.flow_from_dataframe(test_df, x_col="path", 
                                                    y_col="gender", 
                                                    target_size=(img_size,img_size),
                                                    batch_size=batch_size, 
                                                    class_mode='binary',
                                                    shuffle = False)
  
  generators = {'train_gen': train_generator,
                'validation_gen': validation_generator,
                'test_gen': test_generator,
                'predict_gen': predict_generator}
  
  return generators

Generate the most updated `histories` object and explore which models have been fit.

In [ ]:
def save_history():
    hist_out_file = open("histories.pickle", "wb")
    pickle.dump(histories, hist_out_file)
    hist_out_file.close()

def open_history():
    try:
        file = open("histories.pickle", 'rb')
        pickleData = pickle.load(file)
        file.close()
    except (OSError, IOError) as e:
        pickleData = {}
        pickle.dump(pickleData, open("histories.pickle", "wb"))
    return pickleData

In [ ]:
histories = open_history()
histories.keys()

Generate the most updated `performance_df` dataframe.

In [ ]:
def open_performance():
    if os.path.exists('model_performance.csv'):
        return pd.read_csv("model_performance.csv", index_col=False)
    else:
        return pd.DataFrame(columns=['model_name', 'max_val_acc', 'error', 'f1_score', 'roc_auc'])
        
def save_performance(model_name, error, f1, roc_auc):
    new_row = {
        'model_name': model_name,
        'max_val_acc': np.amax(histories[model_name]["val_acc"]),
        'error': error,
        'f1_score': f1,
        'roc_auc': roc_auc
    }
    performance_df = performance_df.append(new_row, ignore_index=True)
    performance_df.to_csv('model_performance.csv', index=False)

In [ ]:
performance_df = open_performance()
performance_df

# Model Functions

The following functions play a part in the training of a model. 

The callbacks `ModelCheckpoint` and `EarlyStopping` are implemented during the training of the model to stop model training before overfitting.

In [ ]:
def mc(title):
    return ModelCheckpoint('./weights/{}.h5'.format(title), 
                           monitor='val_acc', mode='max', verbose=1, save_best_only=True)

es = EarlyStopping(monitor='val_acc', mode='max', min_delta=0.001, verbose=1, patience=5, restore_best_weights=True)

Since all models follow a similar baseleine, a baseline build function `build_model()` is defined with the hyperparameters optimised as default parameters to the function. A general `fit()` function is also called, which trains the model and saves the model history.

In [ ]:
def build_model(tl_model, lr=1e-4, drop_rate=0.5, stacked=False):
    model = models.Sequential()
    model.add(tl_model)      
    model.add(layers.Flatten())
    if stacked:
        model.add(layers.Dense(1024, activation='relu'))
        if drop_rate > 0:
            model.add(layers.Dropout(drop_rate))
    model.add(layers.Dense(1024, activation='relu'))
    if drop_rate > 0:
        model.add(layers.Dropout(drop_rate))
    model.add(layers.Dense(1, activation='sigmoid'))
    
    model.compile(loss='binary_crossentropy', 
                  optimizer=SGD(lr=lr, momentum=0.9),
                  metrics=['acc'])
    
    model.summary()
    return model

In [ ]:
def fit(model, title, generator):
    train_gen = generator['train_gen']
    validation_gen = generator['validation_gen']
    
    history = model.fit(train_gen, 
                      steps_per_epoch=train_gen.samples/train_gen.batch_size, 
                      epochs=50,
                      validation_data=validation_gen,
                      validation_steps=validation_gen.samples/validation_gen.batch_size,
                      verbose=2,
                      callbacks=[es, mc(title)])
    
    histories[title] = history.history
    save_history()

    return history.history

The following functions are used for model evaluation:
1. `plot_curves()` plot the training and validation curves based on the model's training history. `compare_curves()` is a similar method but plots the training histories of multiple models, as defined by `model_names`, on the same plot.
2. `model_analysis()` performs a complete analysis on the performance of the model on the validation dataset. This includes computing the error_rate on the validation dataset, f1_score, roc_auc_score. For greater analysis, the confusion matrix is also plotted alongside a comprehensive classification_report which is generated and saved.

In [ ]:
def plot_curves(model_name):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15,5))
    
    h = histories[model_name]

    ax1.plot(h["loss"], label="Training")
    ax1.plot(h["val_loss"], label="Validation")
    ax1.set_xlabel("# Epochs")
    ax1.set_ylabel("Loss")
    ax1.legend(loc="best")

    ax2.plot(h["acc"], label="Training")
    ax2.plot(h["val_acc"], label="Validation")
    ax2.set_xlabel("# Epochs")
    ax2.set_ylabel("Accuracy")
    ax2.legend(loc="best")

    fig.suptitle("{} Training History".format(model_name))
    plt.savefig("/results/acc_loss_plots/{}_Curves.jpg".format(model_name))

    plt.show()
    
    
def compare_curves(model_names, labels, title):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15,5))
    
    for i, name in enumerate(model_names):
        h = histories[name]
        ax1.plot(h["val_loss"], label=labels[i])
        ax2.plot(h["val_acc"], label=labels[i])

    ax1.set_xlabel("# Epochs")
    ax1.set_ylabel("Loss")
    ax1.legend(loc="best")
    
    ax2.set_xlabel("# Epochs")
    ax2.set_ylabel("Accuracy")
    ax2.legend(loc="best")
    
    fig.suptitle("{} Training Comparison".format(title))
    plt.savefig("/results/acc_loss_plots/{}_Comparison.jpg".format(title))

    plt.show()

In [ ]:
def model_analysis(model, title, pred_gen):
    print('Results for {}'.format(title))
    prediction = model.predict(pred_gen,
                             steps=pred_gen.samples/pred_gen.batch_size,
                             verbose=2)
    predicted_classes = prediction.flatten()
    # Threshold output
    predicted_classes[predicted_classes>=0.5] = 1
    predicted_classes[predicted_classes<0.5] = 0

    actual = pred_gen.classes
    errors = np.where(predicted_classes != actual)[0]
    error_rate = len(errors)/pred_gen.samples
    print("Error rate {}".format(error_rate))
    
    # Geenerate confusion matrix
    genders = ['Female', 'Male']
    cm = confusion_matrix(actual, predicted_classes)
    sns.heatmap(cm, annot=True, cmap='Blues', fmt="d",
              xticklabels=genders, yticklabels=genders)
    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.savefig('results/cm/{}_cm.jpg'.format(title))
    plt.show()

    # Generate classification report
    print(classification_report(actual, predicted_classes, target_names=genders))
    clsf_report = pd.DataFrame(classification_report(actual, predicted_classes, target_names=genders, output_dict=True)).transpose()
    clsf_report.to_csv('results/metrics/{}_cr.csv'.format(title), index= True)

    # Compile all metrics and add to csv
    f1 = f1_score(actual, predicted_classes, average='weighted')
    roc_auc = roc_auc_score(actual, predicted_classes)
    save_performance(title, error_rate, f1, roc_auc)

# Model Architectures

In this section, the various architectures are instantiated with everything except the last block of each transfer learning model is frozen using `layer.trainable = False`

## VGG16

VGG16 takes in an input image size of 224

In [ ]:
generators = generate_data()

In [ ]:
vgg16_net = VGG16(weights='imagenet', include_top=False, input_tensor=None, input_shape=(224,224,3))
vgg16_net.summary()

In [ ]:
for layer in vgg16_net.layers[:-5]:
    layer.trainable = False

In [ ]:
model = build_model(vgg16_net, lr=1e-3)
fit(model, "vgg16", generators)

In [ ]:
plot_curves("vgg16")
model_analysis(model, "vgg16", generators["predict_gen"])

## InceptionV3

InceptionV3 takes in an input image size of 224

In [ ]:
generators = generate_data()

In [6]:
inception_net = InceptionV3(weights='imagenet', include_top=False, input_tensor=None, input_shape=(224,224,3))
inception_net.summary()

87916544/87910968 [==============================] - 9s 0us/step
Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 111, 111, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 111, 111, 32) 0           batch_normalization[0][0]        
______________________

In [ ]:
for layer in inception_net.layers[:-22]:
    layer.trainable = False

In [ ]:
model = build_model(inception_net)
fit(model, "inceptionV3", generators)

In [ ]:
plot_curves("inceptionV3")
model_analysis(model, "inceptionV3", generators["predict_gen"])

## ResNet50

ResNet50 takes in an input image size of 224

In [ ]:
generators = generate_data()

In [6]:
resnet50_conv = ResNet50(weights='imagenet', include_top=False, input_tensor=None, input_shape=(224,224,3))
resnet50_conv.summary()

87916544/87910968 [==============================] - 9s 0us/step
Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 111, 111, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 111, 111, 32) 0           batch_normalization[0][0]        
______________________

In [ ]:
for layer in resnet50_conv.layers[:143]:
    layer.trainable = False

In [ ]:
model = build_model(resnet50_conv)
fit(model, "resnet50", generators)

In [ ]:
plot_curves("resnet50")
model_analysis(model, "resnet50", generators["predict_gen"])

## Xception

Xception takes in an input image size of 224

In [ ]:
generators = generate_data()

In [6]:
xception_model = Xception(weights='imagenet', include_top=False, input_tensor=None, input_shape=(224,224,3))
xception_model.summary()

87916544/87910968 [==============================] - 9s 0us/step
Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 111, 111, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 111, 111, 32) 0           batch_normalization[0][0]        
______________________

In [ ]:
for layer in xception_model.layers[:-6]:
    layer.trainable = False

In [ ]:
model = build_model(xception_model)
fit(model, "xception", generators)

In [ ]:
plot_curves("xception")
model_analysis(model, "xception", generators["predict_gen"])

## InceptionResnetV2

Xception takes in an input image size of 229

In [ ]:
generators = generate_data(img_size=229)

In [6]:
inceptionresnetv2_conv = InceptionResNetV2(weights='imagenet', include_top=False, input_tensor=None, input_shape=(299,299,3))
inceptionresnetv2_conv.summary()

87916544/87910968 [==============================] - 9s 0us/step
Model: "inception_v3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 111, 111, 32) 96          conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 111, 111, 32) 0           batch_normalization[0][0]        
______________________

In [ ]:
for layer in inceptionresnetv2_conv.layers[:759]:
    layer.trainable = False

In [ ]:
model = build_model(inceptionresnetv2_conv)
fit(model, "IncResV2", generators)

In [ ]:
plot_curves("IncResV2")
model_analysis(model, "IncResV2", generators["predict_gen"])

## DenseNet201

Xception takes in an input image size of 224

In [ ]:
generators = generate_data()

In [7]:
denseNet_model = DenseNet201(weights='imagenet', include_top=False, input_tensor=None, input_shape=(224,224,3))
denseNet_model.summary()

74842112/74836368 [==============================] - 10s 0us/step
Model: "densenet201"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
zero_padding2d (ZeroPadding2D)  (None, 230, 230, 3)  0           input_2[0][0]                    
__________________________________________________________________________________________________
conv1/conv (Conv2D)             (None, 112, 112, 64) 9408        zero_padding2d[0][0]             
__________________________________________________________________________________________________
conv1/bn (BatchNormalization)   (None, 112, 112, 64) 256         conv1/conv[0][0]                 
______________________

__________________________________________________________________________________________________
conv5_block13_0_bn (BatchNormal (None, 7, 7, 1280)   5120        conv5_block12_concat[0][0]       
__________________________________________________________________________________________________
conv5_block13_0_relu (Activatio (None, 7, 7, 1280)   0           conv5_block13_0_bn[0][0]         
__________________________________________________________________________________________________
conv5_block13_1_conv (Conv2D)   (None, 7, 7, 128)    163840      conv5_block13_0_relu[0][0]       
__________________________________________________________________________________________________
conv5_block13_1_bn (BatchNormal (None, 7, 7, 128)    512         conv5_block13_1_conv[0][0]       
__________________________________________________________________________________________________
conv5_block13_1_relu (Activatio (None, 7, 7, 128)    0           conv5_block13_1_bn[0][0]         
__________

In [ ]:
for layer in denseNet_model.layers[:-9]:
    layer.trainable = False

In [ ]:
model = build_model(denseNet_model)
fit(model, "densenet", generators)

In [ ]:
plot_curves("densenet")
model_analysis(model, "densenet", generators["predict_gen"])

## Overall Comparison across Base Models

Plot the comparison curves across the 6 base models

In [ ]:
model_names = ["vgg16", "inceptionV3", "resnet50", "xception", "IncResV2", "denseNet"]
compare_curves(model_names, model_names, "Base_Comparison")

# Hyperparameter Optimisation

The 3 best models - VGG16, ResNet50 and DenseNet, are chosen and will have their parameters (batch size, dropout rate, learning rate and presence of stacked fully connected layers). Hence, the following functions were created to prevent any duplication of code

In [ ]:
OPTIMAL_ARCH = ["vgg16", "resnet50", "densenet"]

In [ ]:
def create_tlModel(arch):
    if arch == "vgg16":
        tl_model = VGG16(weights='imagenet', include_top=False, input_tensor=None, input_shape=(224,224,3))
        for layer in tl_model.layers[:-5]:
            layer.trainable = False
    elif arch == "resnet50":
        tl_model = ResNet50(weights='imagenet', include_top=False, input_tensor=None, input_shape=(224,224,3))
        for layer in tl_model.layers[:143]:
            layer.trainable = False
    elif arch == "densenet"
        tl_model = DenseNet201(weights='imagenet', include_top=False, input_tensor=None, input_shape=(224,224,3))
        for layer in tl_model.layers[:-9]:
            layer.trainable = False
    else:
        print("model not found")
        tl_model = None
    return tl_model

## Optimise Batch Size

3 different batch sizes are considered - 64, 128 (base model) and 256. Therefore, each of the three architectures are then rebuilt and trained with the 2 different batch sizes - through the different image generators.

In [ ]:
BATCH_SIZES = [64, 256]
labels = ["bs-128", "bs-64", "bs-256"]

In [ ]:
for bs in BATCH_SIZES:
    generators = generate_data(batch_size=bs)
    for arch in OPTIMAL_ARCH:
        model_name = "{}_bs-{}".format(arch, bs)
        lr = arch == "vgg16" ? 1e-3 : 1e-4
        model = build_model(create_tlModel(arch), lr=lr)
        fit(model, model_name, generators)
        model_analysis(model, model_name, generators["predict_gen"])

In [ ]:
for arch in OPTIMAL_ARCH:
    model_names = [arch]
    for bs in BATCH_SIZES:
        model_names.append("{}_bs-{}".format(arch, bs))
    compare_curves(model_names, labels, "{}_bs-Comparison".format(arch))

## Dropout Rate

3 different dropout values are considered - 0, 0.2 and 0.5 (base model). Therefore each of the three architectures are then rebuilt and trained with the 2 different dropout values - as defined by the parameter `drop_rate` in the `build_model()` function.

In [ ]:
DROP_RATES = [0, 0.2]
labels = ["dr-0.5", "dr-0", "dr-0.2"]
generators = generate_data()

In [ ]:
for dr in DROP_RATES:
    for arch in OPTIMAL_ARCH:
        model_name = "{}_dr-{}".format(arch, dr)
        lr = arch == "vgg16" ? 1e-3 : 1e-4
        model = build_model(create_tlModel(arch), lr=lr, drop_rate=dr)
        fit(model, model_name, generators)
        model_analysis(model, model_name, generators["predict_gen"])

In [ ]:
for arch in OPTIMAL_ARCH:
    model_names = [arch]
    for dr in DROP_RATES:
        model_names.append("{}_dr-{}".format(arch, dr))
    compare_curves(model_names, labels, "{}_dr-Comparison".format(arch))

## Optimise Learning Rate

3 different learning rates are considered - 0.01, 0.001 and 0.0001 (base model). Therefore each of the three architectures are then rebuilt and trained with the 2 different learning rates - as defined by the parameter `lr` in the `build_model()` function. The below code is slightly less straightford since the base vgg16 model differs from the rest of the model, starting with a higher learning rate. 

In [ ]:
LEARNING_RATES = [1e-2, 1e-3]
labels = ["lr-0.0001", "lr-0.01", "lr-0.001"]
generators = generate_data()

In [ ]:
for lr in LEARNING_RATES:
    for arch in OPTIMAL_ARCH:
        if arch == "vgg16" and lr == 1e-3:
            model_name = "vgg16_lr-0.0001"
            model = build_model(create_tlModel(arch), lr=1e-4)
        else:
            model_name = "{}_lr-{}".format(arch, lr)
            model = build_model(create_tlModel(arch), lr=lr)
        fit(model, model_name, generators)
        model_analysis(model, model_name, generators["predict_gen"])

In [ ]:
for arch in OPTIMAL_ARCH:
    model_names = [arch]
    if arch !== "vgg16":
        for lr in LEARNING_RATES:
            model_names.append("{}_lr-{}".format(arch, lr))
        compare_curves(model_names, labels, "{}_lr-Comparison".format(arch))
    else:
        model_names.extend(["vgg16_lr-0.01", "vgg16_lr-0.0001"])
        compare_curves(model_names, ["lr-0.001", "lr-0.01", "lr-0.0001"], "vgg16_lr-Comparison")

## Optimise Stacking

More fully connected layers are optionally added to the base model. Each of the three architectures are then rebuilt and trained with the stacking - as defined by the parameter `stacked` in the `build_model()` function.

In [ ]:
generators = generate_data()
labels = ["unstacked, stacked"]

In [ ]:
for arch in OPTIMAL_ARCH:
    model_name = "{}_stacked".format(arch)
    lr = arch == "vgg16" ? 1e-3 : 1e-4
    model = build_model(create_tlModel(arch), lr=lr, stacked=True)
    fit(model, model_name, generators)
    model_analysis(model, model_name, generators["predict_gen"])

In [ ]:
for arch in OPTIMAL_ARCH:
    model_names = [arch]
    model_names.append("{}_stacked".format(arch))
    compare_curves(model_names, labels, "{}_stacked-Comparison".format(arch))

## Combining Optimal Hyperparameters

In this stage we combine all ideal hyperparameters together to generate the optimal model for this architecture. It is then compared with its base model and each other.

The optimal parameters for each model are as follows:

|          | batch_size | learning_rate | dropout_rate | is_stacked |
|:--------:|:----------:|:-------------:|:------------:|:----------:|
| vgg16    | 64         | 1e-3          | 0.5          | True       |
| resnet50 | 128        | 1e-2          | 0.5          | False      |
| densenet | 128        | 1e-4          | 0.5          | True       |

Since only 1 parameter has changed for both ResNet50 and DenseNet201 architectures, the respective already trained models - `resnet50_lr-0.01` and `densenet_stacked` is used and a new model is created for vgg16.

In [ ]:
# Optimal VGG16
generators = generate_data(batch_size=64)
model = build_model(create_tlModel("vgg16"), lr=1e-3, stacked=True)
fit(model, "vgg16_optimal", generators)
model_analysis(model, "vgg16_optimal", generators["predict_gen"])

In [ ]:
model_names = ["vgg16_optimal", "resnet50_lr-0.01", "densenet_stacked"]
compare_curves(model_names, OPTIMAL_ARCH, "optimal_Comprison")

# Finetuning Models

In this section, we build open our findings of the vgg16 model to further finetune the pretrained transfer learning portion of our model to achieve incrememtal improvements with a signifantly lower learning rate (1e-5).

In [ ]:
generators = generate_data(batch_size=64)

The first experiment is to unfreeze all layers and train the model.

In [ ]:
model = models.load_model("./weights/vgg16_optimal.h5")
for layer in model.layers[0].layers:
    layer.trainable = True

print("Total trainable weights: {}".format(len(model.trainable_weights)))
model.summary()

In [ ]:
fit(model, "vgg16_unfreezeAll", generators)
model_analysis(model, "vgg16_unfreezeAll", generators["predict_gen"])

The second experiment includes freezing back the last block and unfreezing the first block of the preetrained model.

In [ ]:
model = models.load_model("./weights/vgg16_optimal.h5")
for layer in model.layers[0].layers[1:4]:
    layer.trainable = True
for layer in model.layers[0].layers[-5:]:
    layer.trainable = False

print("Total trainable weights: {}".format(len(model.trainable_weights)))
model.summary()

In [ ]:
fit(model, "vgg16_unfreezeTop", generators)
model_analysis(model, "vgg16_unfreezeTop", generators["predict_gen"])

The last experiment includes unfreezing the first block of the preetrained model with the last block still unfrozen.

In [ ]:
model = models.load_model("./weights/vgg16_optimal.h5")
for layer in model.layers[0].layers[1:4]:
    layer.trainable = True

print("Total trainable weights: {}".format(len(model.trainable_weights)))
model.summary()

In [ ]:
fit(model, "vgg16_unfreezeTopBottom", generators)
model_analysis(model, "vgg16_unfreezeTopBottom", generators["predict_gen"])

All the models are then compared with the original base models.

In [ ]:
model_names = ["vgg16_optimal", "vgg16_unfreezeAll", "vgg16_unfreezeTop", "vgg16_unfreezeTopBottom"]
compare_curves(model_names, model_names, "finetuning_Comprison")